force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <pluralLabel>Livraisons</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Numéro de Livraison</label>
        <displayFormat>LIV-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Livraison__c/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <label>Adresse</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/DateExpedition__c.field-meta.xml
<CustomField>
    <fullName>DateExpedition__c</fullName>
    <label>Date Expedition</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/DateReceptionEstimee__c.field-meta.xml
<CustomField>
    <fullName>DateReceptionEstimee__c</fullName>
    <label>Date de Reception Estimee</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Commande</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/StatutLivraison__c.field-meta.xml
<CustomField>
    <fullName>StatutLivraison__c</fullName>
    <label>Statut Livraison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>En préparation</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Échouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <label>Tarif</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <label>Transporteur</label>
    <type>Lookup</type>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>LivraisonsTransporteur</relationshipName>
</CustomField>

force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/StatutLivraison__c.field-meta.xml
<CustomField>
    <fullName>StatutLivraison__c</fullName>
    <label>Statut Livraison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>En cours</fullName>
                <label>n coursE</label>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Échouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <formula>TEXT(Account.TypeClient__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <pluralLabel>Transporteurs</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Nom du Transporteur</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderService.cls
public with sharing class OrderService {

    public static void validateOrderCreation(String typeClient, Integer numberOfProduct){
        if(
            ('Particulier'.equals(typeClient) && numberOfProduct < 3) ||
            ('Professionel'.equals(typeClient) && numberOfProduct < 5)
        ) {
            throw new AuraHandledException('Not enough products');     
        } 
    }

    public static Contract findContractById(Id contractId){
        if (!Schema.sObjectType.Contract.fields.Id.isAccessible() || 
            !Schema.sObjectType.Contract.fields.Status.isAccessible()) {
            throw new AuraHandledException('vous ne pouvez pas faire cette action');
        }
        if (String.isBlank(contractId)) {
            return null;
        }
        return [Select Id, Status from contract where Id = :contractId LIMIT 1 ];
    }

    @AuraEnabled(cacheable=true)
    public static Livraison__c findLivraison(Id orderId) {
        if (!Schema.sObjectType.Livraison__c.fields.Order__c.isAccessible()) {
            throw new AuraHandledException('vous ne pouvez pas faire cette action');
    }
        return [Select Id, Name, Adresse__c, Pays__c, StatutLivraison__c, DateExpedition__c,DateReceptionEstimee__c, Transporteur__c, Order__c, Order__r.TypeClient__c, Tarif__c from Livraison__c where Order__c = :orderId LIMIT 1];
    }
  

}