force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <pluralLabel>Livraisons</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Numéro de Livraison</label>
        <displayFormat>LIV-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Livraison__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/StatutLivraison__c.field-meta.xml
<CustomField>
    <fullName>StatutLivraison__c</fullName>
    <label>Statut Livraison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>En préparation</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Échouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <label>Tarif</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <label>Transporteur</label>
    <type>Lookup</type>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>LivraisonsTransporteur</relationshipName>
</CustomField>

force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/StatutLivraison__c.field-meta.xml
<CustomField>
    <fullName>StatutLivraison__c</fullName>
    <label>Statut Livraison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>En cours</fullName>
                <label>n coursE</label>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Échouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TarifTransporteur__c/TarifTransporteur__c.object-meta.xml
<CustomObject>
    <label>Tarif Transporteur</label>
    <pluralLabel>Tarifs Transporteurs</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Référence Tarif</label>
        <displayFormat>TARIF-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TarifTransporteur__c/fields/DelaiLivraison__c.field-meta.xml
<CustomField>
    <fullName>DelaiLivraison__c</fullName>
    <label>Délai de Livraison (jours)</label>
    <precision>3</precision>
    <scale>0</scale>
    <required>true</required>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TarifTransporteur__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <label>Tarif</label>
    <precision>18</precision>
    <scale>2</scale>
    <required>true</required>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TarifTransporteur__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Tarifs</relationshipLabel>
    <relationshipName>Tarifs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <pluralLabel>Transporteurs</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Nom du Transporteur</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transporteur__c/fields/TypeClientAutorise__c.field-meta.xml
<CustomField>
    <fullName>TypeClientAutorise__c</fullName>
    <label>Types de Client Autorisés</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransporteurSelector.cls
public with sharing class TransporteurSelector {

    @AuraEnabled(cacheable=true)
    public static List<TarifTransporteur__c> getAvailableTransporters(String country, String customerType) {
        if(!Schema.sObjectType.TarifTransporteur__c.fields.Pays__c.isAccessible()||
            !Schema.sObjectType.TarifTransporteur__c.fields.Transporteur__c.isAccessible()||
            !Schema.sObjectType.TarifTransporteur__c.fields.Tarif__c.isAccessible()||
            !Schema.sObjectType.TarifTransporteur__c.fields.Name.isAccessible()
            ){
                throw new AuraHandledException('you do not have access to the required fields');
            }
        try {
            return [
                SELECT Id, Pays__c, Tarif__c, Transporteur__c, Transporteur__r.Name, DelaiLivraison__c
                FROM TarifTransporteur__c
                WHERE Pays__c = :country AND Transporteur__r.TypeClientAutorise__c = :customerType
                ORDER BY Tarif__c ASC, DelaiLivraison__c ASC
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Erreur lors de la récupération des transporteurs.');
        }
    }

    public static Transporteur__c findTransporteurById(Id idTransporteur){
        if (!Schema.sObjectType.Transporteur__c.fields.Id.isAccessible()) {
            throw new AuraHandledException('vous ne pouvez pas faire cette action');
        }
        return [SELECT Id, Name FROM Transporteur__c WHERE Id = :idTransporteur];
    }

    public static TarifTransporteur__c findTarifTransporteur(Id idTransporteur, String pays){
        if (!Schema.sObjectType.TarifTransporteur__c.fields.Id.isAccessible()) {
            throw new AuraHandledException('vous ne pouvez pas faire cette action');
        }
        return [SELECT Id, Tarif__c, Transporteur__c, Pays__c, DelaiLivraison__c FROM TarifTransporteur__c WHERE Transporteur__c = :idTransporteur and Pays__c = :pays];
    }

    @AuraEnabled
    public static Livraison__c setTransporteur(Id idLivraison, Id idTransporteur){
        if (!Schema.sObjectType.Livraison__c.fields.Transporteur__c.isUpdateable()||
            !Schema.sObjectType.Livraison__c.fields.StatutLivraison__c.isUpdateable()||
            !Schema.sObjectType.Livraison__c.fields.Tarif__c.isUpdateable()) {
            throw new AuraHandledException('vous ne pouvez pas faire cette action');
        }
        try {
            Livraison__c livraison = [Select Id, Pays__c from Livraison__c where Id =:idLivraison];
            livraison.Transporteur__c = idTransporteur;
            livraison.StatutLivraison__c = 'En préparation';
            livraison.Tarif__c = [SELECT Tarif__c FROM TarifTransporteur__c WHERE Transporteur__c = :idTransporteur and Pays__c = :livraison.Pays__c].Tarif__c;

            update livraison;
            return livraison;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}