force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <pluralLabel>Livraisons</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Numéro de Livraison</label>
        <displayFormat>LIV-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Livraison__c/fields/DateExpedition__c.field-meta.xml
<CustomField>
    <fullName>DateExpedition__c</fullName>
    <label>Date Expedition</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/DateReceptionEstimee__c.field-meta.xml
<CustomField>
    <fullName>DateReceptionEstimee__c</fullName>
    <label>Date de Reception Estimee</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/StatutLivraison__c.field-meta.xml
<CustomField>
    <fullName>StatutLivraison__c</fullName>
    <label>Statut Livraison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>En préparation</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Échouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <label>Transporteur</label>
    <type>Lookup</type>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>LivraisonsTransporteur</relationshipName>
</CustomField>

force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/StatutLivraison__c.field-meta.xml
<CustomField>
    <fullName>StatutLivraison__c</fullName>
    <label>Statut Livraison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>En cours</fullName>
                <label>n coursE</label>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Échouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TarifTransporteur__c/TarifTransporteur__c.object-meta.xml
<CustomObject>
    <label>Tarif Transporteur</label>
    <pluralLabel>Tarifs Transporteurs</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Référence Tarif</label>
        <displayFormat>TARIF-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TarifTransporteur__c/fields/DelaiLivraison__c.field-meta.xml
<CustomField>
    <fullName>DelaiLivraison__c</fullName>
    <label>Délai de Livraison (jours)</label>
    <precision>3</precision>
    <scale>0</scale>
    <required>true</required>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TarifTransporteur__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Tarifs</relationshipLabel>
    <relationshipName>Tarifs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <pluralLabel>Transporteurs</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Nom du Transporteur</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderTriggerHandler.cls
public with sharing class OrderTriggerHandler {

    public static void handleOrder(Order order) {
        if (!Schema.sObjectType.Livraison__c.fields.Id.isAccessible()) {
            throw new AuraHandledException('vous ne pouvez pas faire cette action');
        }
        Livraison__c livraison = OrderService.findLivraison(order.Id);
        if (livraison.Transporteur__c == null) {
             order.addError('Choisissez un transporteur');
             return;
        }
         Transporteur__c transporteur =  TransporteurSelector.findTransporteurById(livraison.Transporteur__c);
         TarifTransporteur__c tarif = TransporteurSelector.findTarifTransporteur(transporteur.Id, order.Pays__c);
         Contract contract = OrderService.findContractById(order.ContractId);
         if(contract.Status == 'Draft') {
             contract.Status = 'Activated';
             update contract;
         }
         livraison.DateExpedition__c = System.today();
         livraison.DateReceptionEstimee__c = System.today().addDays( Integer.valueOf(tarif.DelaiLivraison__c));
         livraison.StatutLivraison__c = 'Expédiée';
         update livraison;

    }
}