force-app/main/default/objects/Account/fileds/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <label>Type Client</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <pluralLabel>Livraisons</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Numéro de Livraison</label>
        <displayFormat>LIV-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Livraison__c/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <label>Adresse</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Commande</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <formula>TEXT(Account.TypeClient__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler {

    public static void handleOpportunity(Opportunity opp) {

            Account acc = AccountSelector.getAccountById(opp.AccountId);

            Integer productCount=  OpportunityLineItemSelector.getNumberOfProduct(opp.Id);

            OrderService.validateOrderCreation(acc.TypeClient__c, productCount);

            List<OpportunityLineItem> linesItem = OpportunityLineItemSelector.getLineItems(opp.Id);

            Contract contract = new Contract(
                AccountId = opp.AccountId,
                Status = 'Draft',
                StartDate = System.today(),
                ContractTerm = 12
            );

            insert contract;

             Order newOrder = new Order(
                AccountId = opp.AccountId,  // Associer l'Order à l'Account
                OpportunityId  = opp.Id,    // Associer l'Order à l'Opportunity
                Status = 'Draft',
                ContractId = contract.Id,
                Type = 'New',
                Pays__c = acc.ShippingState,
                EffectiveDate=System.today(),
                ShippingStreet = acc.ShippingStreet,
                ShippingCity = acc.ShippingCity,
                ShippingState = acc.ShippingState,
                ShippingPostalCode = acc.ShippingPostalCode,
                ShippingCountry = acc.ShippingCountry,
                Pricebook2Id = opp.Pricebook2Id
            );
            insert newOrder;


            for(OpportunityLineItem item: linesItem){
                OrderItem orderItem = new OrderItem(
                    Product2Id= item.Product2Id,
                    OrderId=newOrder.Id,
                    Quantity=item.Quantity,
                    UnitPrice=item.UnitPrice,
                    ListPrice=item.UnitPrice,
                    PricebookEntryId=item.PricebookEntryId
                );
                insert orderItem;
            }

            Livraison__c livraison = new Livraison__c (
                Order__c = newOrder.Id,
                Adresse__c = acc.ShippingStreet + ' ' + acc.ShippingCity + '' + acc.ShippingState + ' ' + acc.ShippingPostalCode + ' ' + acc.ShippingCountry,
                Pays__c = acc.ShippingState,
                CodePostal__c = acc.ShippingPostalCode
            );
            insert livraison;


    }
}